site_name: IHC - Grupo 4
site_description: Avaliação Crítica e Guia de Acessibilidade Digital
site_author: Grupo 4 - UnB FCTE

theme:
  name: material
  language: pt-BR
  features:
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - toc.integrate

nav:
  - Início: index.md
  - Guia de Acessibilidade:
    - 1. Engenharia de UX: guia/ux.md
    - 2. Marco Normativo: guia/normas.md
    - 3. Ferramentas de Auditoria: guia/ferramentas.md
    - 4. Checklist Interativo: guia/checklist.md

plugins:
  - search:
      lang: pt